# Funding options for RAG Guardian
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors
# github: gacabartosz

# Other platforms
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# otechie:
# lfx_crowdfunding:

# Custom URL (your website, buy me a coffee, etc.)
custom: ["https://bartoszgaca.pl"]
