name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        # Issues
        stale-issue-message: |
          This issue has been automatically marked as stale because it has not had recent activity.
          It will be closed in 7 days if no further activity occurs.

          If you believe this issue is still relevant, please:
          - Add a comment explaining why it should remain open
          - Remove the "stale" label

          Thank you for your contributions! 🙏

        close-issue-message: |
          This issue has been automatically closed due to inactivity.

          If you still think this is relevant, feel free to reopen it or create a new issue with updated information.

        days-before-stale: 60
        days-before-close: 7
        stale-issue-label: 'stale'
        exempt-issue-labels: 'pinned,security,roadmap,help wanted,good first issue'

        # Pull Requests
        stale-pr-message: |
          This pull request has been automatically marked as stale because it has not had recent activity.
          It will be closed in 14 days if no further activity occurs.

          If you're still working on this, please:
          - Push new commits
          - Add a comment with your progress
          - Remove the "stale" label

          Thank you for your contribution! 🚀

        close-pr-message: |
          This pull request has been automatically closed due to inactivity.

          If you'd like to continue working on this, feel free to reopen it or create a new PR.

        days-before-pr-stale: 30
        days-before-pr-close: 14
        stale-pr-label: 'stale'
        exempt-pr-labels: 'pinned,security,work-in-progress'

        # Operations
        operations-per-run: 100
        remove-stale-when-updated: true
